### ISSUE TITLE
GetInstanceID persistance

### ISSUE THREAD

**Issue by STARasGAMES** [Casey-Hofland/GameSettings#2]
Hi
I looked at the code and found this line in the GameSettings/Runtime/Base/GameSetting.cs:
```c#
protected string saveKey => $"GameSettings/{settingName}/{GetInstanceID()}";
```

Are you sure that GetInstanceID() is persistent?
From my experience, it changes after restarting unity or player

**Comment by CaseyHofland** [comment]
http://answers.unity.com/answers/863118/view.html

This was what I’d found out about it. In short: in builds it works fine. It’s wasteful though.

However, I am working on a whole new version of this from my experience with this first version, so this won’t be fixed. Saving will also be done in a different way, but the genesis of it is that you don’t really need to save each setting, just save a quality level called “Custom”.

**Comment by CaseyHofland** [comment]
You know what? There was still some GetInstanceID creeping up in my new system, so thanks for reminding me to check it out!
